services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        value: your-mysql-url
    pythonVersion: 3.11.9
